version: 2.1

jobs:
  craftech:
    docker:
      - image: nginx:1.14.2-alpine
    steps:
      - checkout
      - run:
          name: "login"
          command: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
      - run:
          name: "Build"
          command: "docker build -t JJorgemartin/challengeCraftech-3:$CIRCLE_SHA1"
      - run:
          name: "Push"
          command: "docker push JJorgemartin/challengeCraftech-3:$CIRCLE_SHA1"


workflows:
  craftech-workflow:
    jobs:
      - craftech
