version: 2.1

jobs:
  craftech:
    docker:
      - image: seniorjj/challenge:1.0
    steps:
      - checkout
      - run:
          name: "login"
          command: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
      - run:
          name: "Build"
          command: "docker build -t jjorgemartin/challengecraftech-3:$CIRCLE_SHA1 ."
      - run:
          name: "Push"
          command: "docker push jjorgemartin/challengecraftech-3:$CIRCLE_SHA1"


workflows:
  craftech-workflow:
    jobs:
      - craftech
